### ISSUE TITLE
Mix of tabs & spaces for indentation

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alphred#1]
Means the indentation is messed up in, for example, [the GitHub preview](https://github.com/shawnrice/alphred/blob/master/classes/Index.php#L504).

![alphred-indentation](https://cloud.githubusercontent.com/assets/747913/5599567/b3e2b134-92c9-11e4-97be-58f5492d9df7.png)

**Comment by shawnrice** [comment]
Erg. I was playing around with [php beautifier](http://pear.php.net/package/PHP_Beautifier/) and screwing with ST3 configs... that's what probably led to this.
