### ISSUE TITLE
Problem creating server scripts

### ISSUE THREAD

**Issue by vdesabou** [shawnrice/alphred#2]
Hi Shawn,

I wanted to test Alphred but unless I'm missing something, the `php Alphred.phar create-server-scripts` is not creating the files

```
php Alphred.phar create-server-scripts
Do you want to create the server scripts to run this workflow from a CLI Server SAPI? (Y/n): y
Files will be created at /Users/vdesabou/Downloads. Continue? (Y/n): y
================================================================================
 Alphred (0.9.0)
================================================================================

Three scripts have been created.
1. server.sh
2. kill.sh
3. server.php
snip
```

But then I don't have any generated files in /Users/vdesabou/Downloads.

How Can I troubleshoot this?

**Comment by shawnrice** [comment]
Good catch. I had some problems in `Main.php`. I went ahead and fixed it. For now, just do:

``` shell
php Alphred.phar update-self-master
php Alphred.phar create-server-scripts
```

and it should work.

The server scripts are experimental, so let me know how they work.

**Comment by vdesabou** [comment]
Thanks, with the updated I could create the scripts
